'use client';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// V65 ZOOM AVANT 1er CERCLE 0.62*1.00 TANGENT + NOYAU -30% 70% + DEZOOM CORRIGE 0.92 + DIAMANT REFLECTION
export default function Page(){
 const ref=useRef<HTMLDivElement>(null);
 const dmxRef=useRef({ch1:127,ch2:85,ch3:165,ch10:210});
 const [on,setOn]=useState(false);
 const [dmxOn,setDmxOn]=useState(false);
 const [mods,setMods]=useState({webgpu:false,audio:false,midi:false,osc:true});
 useEffect(()=>{
  const mount=ref.current!; const scene=new THREE.Scene(); scene.background=new THREE.Color(0x000000);
  const camera=new THREE.PerspectiveCamera(34,window.innerWidth/window.innerHeight,0.1,100); camera.position.set(0,0,10.2);
  const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setSize(window.innerWidth,window.innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,1.25)); renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=0.82; mount.appendChild(renderer.domElement);
  const composer=new EffectComposer(renderer); composer.addPass(new RenderPass(scene,camera)); const bloom=new UnrealBloomPass(new THREE.Vector2(window.innerWidth,window.innerHeight),0.52,0.44,0.84); composer.addPass(bloom);
  const cubeRenderTarget=new THREE.WebGLCubeRenderTarget(256); (cubeRenderTarget.texture as any).type=THREE.HalfFloatType;
  const cubeCamera=new THREE.CubeCamera(0.1,100,cubeRenderTarget); scene.add(cubeCamera);
  setMods({webgpu:false,audio:false,midi:false,osc:true});
  if(typeof navigator!=='undefined' && (navigator as any).gpu){ (navigator as any).gpu.requestAdapter({powerPreference:'high-performance'}).then((a:any)=>{ if(a) setMods(m=>({...m,webgpu:true})); }); }
  let ws:any=null; let retry=0; const connectWS=()=>{ try{ ws=new WebSocket('ws://localhost:8081'); ws.onopen=()=>{ retry=0; setDmxOn(true); }; ws.onmessage=(e:any)=>{ try{ const msg=JSON.parse(e.data); if(msg.channels){ const c=msg.channels; const clamp=(v:number)=>Math.max(0,Math.min(255,Math.floor(v))); dmxRef.current={ch1:clamp(c[0]),ch2:clamp(c[1]),ch3:clamp(c[2]),ch10:clamp(c[9])}; } }catch{} }; ws.onclose=()=>{ setDmxOn(false); setTimeout(connectWS,Math.min(10000,400*Math.pow(2,retry++))); }; ws.onerror=()=>{ try{ws.close();}catch{} }; }catch{} }; connectWS();
  try{ const AudioCtx=(window as any).AudioContext || (window as any).webkitAudioContext; const ctx=new AudioCtx(); const analyser=ctx.createAnalyser(); analyser.fftSize=256; const osc=ctx.createOscillator(); osc.frequency.value=110; osc.connect(analyser); analyser.connect(ctx.destination); osc.start(); const loop=()=>{ analyser.getByteFrequencyData(new Uint8Array(128)); setMods(m=>({...m,audio:true})); requestAnimationFrame(loop); }; loop(); }catch{}
  try{ if((navigator as any).requestMIDIAccess){ (navigator as any).requestMIDIAccess().then(()=>setMods(m=>({...m,midi:true}))); } }catch{}
  // NOYAU -30% = 70% *0.70
  scene.add(new THREE.AmbientLight(0xffffff,0.57));
  const key=new THREE.PointLight(0xffffff,115,50); key.position.set(4,4,5); scene.add(key);
  const fill=new THREE.PointLight(0xaaccff,68,50); fill.position.set(-5,3,4); scene.add(fill);
  const coreLight=new THREE.PointLight(0xffffff,80,24); scene.add(coreLight);
  const coreLight2=new THREE.PointLight(0xffffff,54,18); coreLight2.position.set(0,0,2.2); scene.add(coreLight2);
  // ZOOM AVANT: 0.56 -> 0.92 (1er cercle touche 6 pts)
  const coreGroup=new THREE.Group(); (coreGroup as any).scale.setScalar(0.92); scene.add(coreGroup);
  const cageGroup=new THREE.Group(); coreGroup.add(cageGroup); const branchGroup=new THREE.Group(); coreGroup.add(branchGroup); const satGroup=new THREE.Group(); coreGroup.add(satGroup);
  // 1er CERCLE 0.62 = REFERENCE TANGENT
  const outer=new THREE.Mesh(new THREE.IcosahedronGeometry(0.62,3),new THREE.MeshBasicMaterial({color:0xffffff,wireframe:true,transparent:true,opacity:0.62} as any)); cageGroup.add(outer);
  const outer2=new THREE.Mesh(new THREE.IcosahedronGeometry(0.78,2),new THREE.MeshBasicMaterial({color:0x88ccff,wireframe:true,transparent:true,opacity:0.38} as any)); cageGroup.add(outer2);
  const outer3=new THREE.Mesh(new THREE.IcosahedronGeometry(0.92,1),new THREE.MeshBasicMaterial({color:0xffffff,wireframe:true,transparent:true,opacity:0.22} as any)); cageGroup.add(outer3);
  const RADIUS_FACTOR=1.00;
  const branches:any[]=[]; const satPos:THREE.Vector3[]=[]; for(let i=0;i<6;i++){ const a=i*60*Math.PI/180; satPos.push(new THREE.Vector3(Math.cos(a)*0.62*RADIUS_FACTOR,Math.sin(a)*0.62*RADIUS_FACTOR,0)); }
  const mkBranch=(p1:THREE.Vector3,p2:THREE.Vector3)=>{ const dir=p2.clone().sub(p1); const len=dir.length(); const cyl=new THREE.CylinderGeometry(0.0072,0.0072,len,10); const mat=new THREE.MeshPhysicalMaterial({color:0xffffff,emissive:0xaaffff,emissiveIntensity:1.15,transmission:0.96,thickness:0.52,ior:2.417,roughness:0.01,clearcoat:1.0,reflectivity:0.98,envMapIntensity:2.2,transparent:true,opacity:0.52} as any); const mesh=new THREE.Mesh(cyl,mat); mesh.position.copy(p1.clone().add(p2).multiplyScalar(0.5)); mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.clone().normalize()); branchGroup.add(mesh); const octa=new THREE.Mesh(new THREE.OctahedronGeometry(0.028,0),new THREE.MeshPhysicalMaterial({color:0xffffff,emissive:0xffffff,emissiveIntensity:0.82,transmission:0.98,thickness:0.62,ior:2.417,transparent:true,opacity:0.52} as any)); octa.position.copy(p2); branchGroup.add(octa); const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([p1,p2]),new THREE.LineBasicMaterial({color:0x88ffff,transparent:true,opacity:0.58} as any)); branchGroup.add(line); branches.push({mesh,mat,line,octa,p1,p2}); };
  satPos.forEach((p,i)=>{ mkBranch(new THREE.Vector3(0,0,0),p); mkBranch(p,satPos[(i+1)%6]); mkBranch(p,p.clone().normalize().multiplyScalar(1.02)); }); for(let i=0;i<48;i++){ const a=new THREE.Vector3().randomDirection().multiplyScalar(0.62*0.88); const b=new THREE.Vector3().randomDirection().multiplyScalar(0.62*0.88); mkBranch(a,b); }
  const flowGeo=new THREE.BufferGeometry(); const flowCount=384; const flowPos=new Float32Array(flowCount*3); for(let i=0;i<flowCount;i++){ const b=branches[i%branches.length]; const t=Math.random(); flowPos[i*3]=b.p1.x+(b.p2.x-b.p1.x)*t; flowPos[i*3+1]=b.p1.y+(b.p2.y-b.p1.y)*t; flowPos[i*3+2]=b.p1.z+(b.p2.z-b.p1.z)*t; } flowGeo.setAttribute('position',new THREE.BufferAttribute(flowPos,3)); const flowMat=new THREE.PointsMaterial({color:0x88ffff,size:0.042,transparent:true,opacity:0.48} as any); branchGroup.add(new THREE.Points(flowGeo,flowMat));
  const diamV='varying vec3 vN; varying vec3 vV; varying vec2 vUv; void main(){ vUv=uv; vN=normalize(normalMatrix*normal); vec4 mv=modelViewMatrix*vec4(position,1.0); vV=-mv.xyz; gl_Position=projectionMatrix*mv; }';
  const diamF='varying vec3 vN; varying vec3 vV; varying vec2 vUv; uniform float uT; uniform float uI; uniform float uE; uniform samplerCube uEnv; void main(){ float ang=atan(vUv.y-0.5,vUv.x-0.5); float rad=length(vUv-0.5)*2.0; float sector=mod(ang*4.0/3.14159+uT*0.12,8.0); float arrow=pow(abs(sin(sector*3.14159)),22.0)*0.52; float star=pow(cos(ang*8.0),36.0)*0.38*exp(-rad*2.0); float f=pow(1.0-dot(normalize(vN),normalize(vV)),1.9); vec3 R=reflect(-normalize(vV),normalize(vN)); vec3 env=textureCube(uEnv,R).rgb; float c=0.32+uI*0.24+arrow*0.82+star+f*0.28*uI; vec3 base=vec3(0.74,0.88,1.0)+env*0.28+f*0.42; base+=vec3(0.92,0.96,1.0)*arrow*1.1; base*=uE; gl_FragColor=vec4(base*c,0.72); }';
  const middleMat=new THREE.ShaderMaterial({uniforms:{uT:{value:0},uI:{value:0},uE:{value:0.58},uEnv:{value:cubeRenderTarget.texture}},vertexShader:diamV,fragmentShader:diamF,transparent:true,side:THREE.DoubleSide} as any); const middle=new THREE.Mesh(new THREE.IcosahedronGeometry(0.48,5),middleMat); coreGroup.add(middle);
  const innerMat=new THREE.MeshPhysicalMaterial({color:0xffffff,emissive:0x88ccff,emissiveIntensity:0.38,transmission:1.0,thickness:0.88,ior:2.417,roughness:0.01,clearcoat:1.0,envMap:cubeRenderTarget.texture,envMapIntensity:1.2,transparent:true,opacity:0.62} as any); const inner=new THREE.Mesh(new THREE.IcosahedronGeometry(0.22,4),innerMat); coreGroup.add(inner);
  const inner2Mat=new THREE.MeshPhysicalMaterial({color:0xaaffff,emissive:0xaaffff,emissiveIntensity:0.48,transmission:1.0,thickness:0.72,ior:2.417,roughness:0.01,clearcoat:1.0,envMap:cubeRenderTarget.texture,envMapIntensity:1.6,transparent:true,opacity:0.68} as any); const inner2=new THREE.Mesh(new THREE.IcosahedronGeometry(0.11,3),inner2Mat); coreGroup.add(inner2);
  const glow=new THREE.Mesh(new THREE.SphereGeometry(0.30,32,32),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:0.08} as any)); coreGroup.add(glow); const glow2=new THREE.Mesh(new THREE.SphereGeometry(0.52,32,32),new THREE.MeshBasicMaterial({color:0x88ccff,transparent:true,opacity:0.05} as any)); coreGroup.add(glow2);
  for(let i=0;i<6;i++){ const ang=i*60*Math.PI/180; const m=new THREE.Mesh(new THREE.SphereGeometry(0.038,16,16),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:0.96} as any)); m.position.set(Math.cos(ang)*0.62*RADIUS_FACTOR,Math.sin(ang)*0.62*RADIUS_FACTOR,0); satGroup.add(m); const l=new THREE.PointLight(0xffffff,42,3.0); l.position.copy(m.position); satGroup.add(l); }
  const partGeo=new THREE.BufferGeometry(); const partPos=new Float32Array(256*3); for(let i=0;i<256;i++){ const th=i*2.399963; const ph=Math.acos(1-2*i/256); const r=1.6+Math.random()*1.8; partPos[i*3]=Math.sin(ph)*Math.cos(th)*r; partPos[i*3+1]=Math.sin(ph)*Math.sin(th)*r; partPos[i*3+2]=Math.cos(ph)*r; } partGeo.setAttribute('position',new THREE.BufferAttribute(partPos,3)); const partMat=new THREE.PointsMaterial({color:0x88ffff,size:0.016,transparent:true,opacity:0.38} as any); const particles=new THREE.Points(partGeo,partMat); scene.add(particles);
  let ignited=false; const ignite=()=>{ if(ignited) return; ignited=true; setOn(true); bloom.strength=0.52; (bloom as any).radius=0.44; (innerMat as any).emissiveIntensity=1.12; inner.scale.setScalar(1.04); inner2.scale.setScalar(1.08); glow.scale.setScalar(1.12); middleMat.uniforms.uE.value=0.72; coreLight.intensity=80; coreLight2.intensity=54; renderer.toneMappingExposure=0.82; branches.forEach((b:any)=>{ b.mat.opacity=0.92; b.mat.emissiveIntensity=2.4; b.line.material.opacity=0.78; }); flowMat.opacity=0.82; partMat.opacity=0.58; }; setTimeout(ignite,180); window.addEventListener('pointerdown',ignite,{once:true}); window.addEventListener('touchstart',ignite,{once:true});
  let t=0; let raf=0; const flowSpeeds=new Float32Array(384).map(()=>Math.random()); const animate=()=>{ raf=requestAnimationFrame(animate); t+=0.016; middle.visible=false; cubeCamera.position.copy(middle.position); cubeCamera.update(renderer,scene); middle.visible=true; middleMat.uniforms.uT.value=t; middleMat.uniforms.uI.value=0.38+Math.sin(t*2.2)*0.08+(ignited?0.20:0); const dmx=dmxRef.current; const master=dmx.ch10/255; const prop=(dmx.ch1/255)*0.9*master; const bloomMod=(dmx.ch2/255)*0.22; bloom.strength=0.52+bloomMod*0.22; const flowMod=(dmx.ch3/255)*0.92; const fPos=flowGeo.attributes.position.array as Float32Array; for(let i=0;i<384;i++){ const b=branches[i%branches.length]; flowSpeeds[i]+=0.016+0.010+flowMod*0.014; if(flowSpeeds[i]>1) flowSpeeds[i]=0; const tt=flowSpeeds[i]; fPos[i*3]=b.p1.x+(b.p2.x-b.p1.x)*tt; fPos[i*3+1]=b.p1.y+(b.p2.y-b.p1.y)*tt; fPos[i*3+2]=b.p1.z+(b.p2.z-b.p1.z)*tt; } flowGeo.attributes.position.needsUpdate=true; const rot=0.0014*(0.5+prop); coreGroup.rotation.y+=rot; branchGroup.rotation.y-=rot*0.38; cageGroup.rotation.y+=rot*0.24; middle.rotation.y+=rot*0.52; inner.rotation.y-=rot*0.52; inner2.rotation.y+=rot*0.72; satGroup.rotation.z+=rot*0.28; particles.rotation.y+=0.0022; composer.render(); }; animate();
  const onResize=()=>{ camera.aspect=window.innerWidth/window.innerHeight; camera.updateProjectionMatrix(); renderer.setSize(window.innerWidth,window.innerHeight); composer.setSize(window.innerWidth,window.innerHeight); }; window.addEventListener('resize',onResize);
  return()=>{ cancelAnimationFrame(raf); window.removeEventListener('resize',onResize); mount.removeChild(renderer.domElement); renderer.dispose(); if(ws) ws.close(); };
 },[]);
 return(<div style={{width:'100%',height:'100dvh',background:'#000',overflow:'hidden',touchAction:'none'}}><div ref={ref} style={{position:'fixed',inset:0}}/><div style={{position:'fixed',top:12,left:'50%',transform:'translateX(-50%)',background:on?'#88ffff':'#3dd598',color:'#000',padding:'8px 20px',borderRadius:999,fontSize:11,fontWeight:900,letterSpacing:'0.15em',zIndex:10}}>{on?'V65 ZOOM AVANT 0.62*1.00 TANGENT NOYAU -30% '+(dmxOn?'DMX WS':'DMX SYNTH')+' '+Object.values(mods).filter(Boolean).length+'/4 MODS':'IGNITION V65'}</div><div style={{position:'fixed',bottom:0,left:0,right:0,zIndex:10,padding:12}}><button style={{padding:14,borderRadius:999,border:0,background:'#fff',color:'#000',fontSize:12,fontWeight:900,letterSpacing:'0.12em'}}>V65 1er CERCLE 0.62*1.00 TANGENT ZOOM AVANT 0.92 NOYAU -30% 70% REFLECTION DIAMANT 8-ARROWS</button></div></div>);
}
